# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

import math
import typing as T

import numpy
import sym


def compute_prior(dt, x, p):
    # type: (float, numpy.ndarray, numpy.ndarray) -> T.Tuple[numpy.ndarray, numpy.ndarray]
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        dt: Scalar
        x: Matrix81
        p: Matrix88

    Outputs:
        x_hat: Matrix81
        p_hat: Matrix88
    """

    # Total ops: 241

    # Input arrays
    if x.shape == (8,):
        x = x.reshape((8, 1))
    elif x.shape != (8, 1):
        raise IndexError(
            "x is expected to have shape (8, 1) or (8,); instead had shape {}".format(
                x.shape
            )
        )

    # Intermediate terms (33)
    _tmp0 = 1.0 * dt
    _tmp1 = dt * p[2, 2] + 1.0 * p[0, 2]
    _tmp2 = dt * p[3, 2] + 1.0 * p[1, 2]
    _tmp3 = 1.0 * p[2, 2]
    _tmp4 = 1.0 * p[3, 2]
    _tmp5 = dt * p[6, 2] + 1.0 * p[4, 2]
    _tmp6 = dt * p[7, 2] + 1.0 * p[5, 2]
    _tmp7 = 1.0 * p[6, 2]
    _tmp8 = 1.0 * p[7, 2]
    _tmp9 = dt * p[2, 3] + 1.0 * p[0, 3]
    _tmp10 = dt * p[3, 3] + 1.0 * p[1, 3]
    _tmp11 = 1.0 * p[2, 3]
    _tmp12 = 1.0 * p[3, 3]
    _tmp13 = dt * p[6, 3] + 1.0 * p[4, 3]
    _tmp14 = dt * p[7, 3] + 1.0 * p[5, 3]
    _tmp15 = 1.0 * p[6, 3]
    _tmp16 = 1.0 * p[7, 3]
    _tmp17 = dt * p[2, 6] + 1.0 * p[0, 6]
    _tmp18 = dt * p[3, 6] + 1.0 * p[1, 6]
    _tmp19 = 1.0 * p[2, 6]
    _tmp20 = 1.0 * p[3, 6]
    _tmp21 = dt * p[6, 6] + 1.0 * p[4, 6]
    _tmp22 = dt * p[7, 6] + 1.0 * p[5, 6]
    _tmp23 = 1.0 * p[6, 6]
    _tmp24 = 1.0 * p[7, 6]
    _tmp25 = dt * p[2, 7] + 1.0 * p[0, 7]
    _tmp26 = dt * p[3, 7] + 1.0 * p[1, 7]
    _tmp27 = 1.0 * p[2, 7]
    _tmp28 = 1.0 * p[3, 7]
    _tmp29 = dt * p[6, 7] + 1.0 * p[4, 7]
    _tmp30 = dt * p[7, 7] + 1.0 * p[5, 7]
    _tmp31 = 1.0 * p[6, 7]
    _tmp32 = 1.0 * p[7, 7]

    # Output terms
    _x_hat = numpy.zeros(8)
    _x_hat[0] = _tmp0 * x[2, 0] + x[0, 0]
    _x_hat[1] = _tmp0 * x[3, 0] + x[1, 0]
    _x_hat[2] = x[2, 0]
    _x_hat[3] = x[3, 0]
    _x_hat[4] = _tmp0 * x[6, 0] + x[4, 0]
    _x_hat[5] = _tmp0 * x[7, 0] + x[5, 0]
    _x_hat[6] = x[6, 0]
    _x_hat[7] = x[7, 0]
    _p_hat = numpy.zeros((8, 8))
    _p_hat[0, 0] = _tmp1 * dt + 1.0 * dt * p[2, 0] + 1.0 * p[0, 0] + 1
    _p_hat[1, 0] = _tmp2 * dt + 1.0 * dt * p[3, 0] + 1.0 * p[1, 0]
    _p_hat[2, 0] = _tmp3 * dt + 1.0 * p[2, 0]
    _p_hat[3, 0] = _tmp4 * dt + 1.0 * p[3, 0]
    _p_hat[4, 0] = _tmp5 * dt + 1.0 * dt * p[6, 0] + 1.0 * p[4, 0]
    _p_hat[5, 0] = _tmp6 * dt + 1.0 * dt * p[7, 0] + 1.0 * p[5, 0]
    _p_hat[6, 0] = _tmp7 * dt + 1.0 * p[6, 0]
    _p_hat[7, 0] = _tmp8 * dt + 1.0 * p[7, 0]
    _p_hat[0, 1] = _tmp9 * dt + 1.0 * dt * p[2, 1] + 1.0 * p[0, 1]
    _p_hat[1, 1] = _tmp10 * dt + 1.0 * dt * p[3, 1] + 1.0 * p[1, 1] + 1
    _p_hat[2, 1] = _tmp11 * dt + 1.0 * p[2, 1]
    _p_hat[3, 1] = _tmp12 * dt + 1.0 * p[3, 1]
    _p_hat[4, 1] = _tmp13 * dt + 1.0 * dt * p[6, 1] + 1.0 * p[4, 1]
    _p_hat[5, 1] = _tmp14 * dt + 1.0 * dt * p[7, 1] + 1.0 * p[5, 1]
    _p_hat[6, 1] = _tmp15 * dt + 1.0 * p[6, 1]
    _p_hat[7, 1] = _tmp16 * dt + 1.0 * p[7, 1]
    _p_hat[0, 2] = 1.0 * _tmp1
    _p_hat[1, 2] = 1.0 * _tmp2
    _p_hat[2, 2] = _tmp3 + 1
    _p_hat[3, 2] = _tmp4
    _p_hat[4, 2] = 1.0 * _tmp5
    _p_hat[5, 2] = 1.0 * _tmp6
    _p_hat[6, 2] = _tmp7
    _p_hat[7, 2] = _tmp8
    _p_hat[0, 3] = 1.0 * _tmp9
    _p_hat[1, 3] = 1.0 * _tmp10
    _p_hat[2, 3] = _tmp11
    _p_hat[3, 3] = _tmp12 + 1
    _p_hat[4, 3] = 1.0 * _tmp13
    _p_hat[5, 3] = 1.0 * _tmp14
    _p_hat[6, 3] = _tmp15
    _p_hat[7, 3] = _tmp16
    _p_hat[0, 4] = _tmp17 * dt + 1.0 * dt * p[2, 4] + 1.0 * p[0, 4]
    _p_hat[1, 4] = _tmp18 * dt + 1.0 * dt * p[3, 4] + 1.0 * p[1, 4]
    _p_hat[2, 4] = _tmp19 * dt + 1.0 * p[2, 4]
    _p_hat[3, 4] = _tmp20 * dt + 1.0 * p[3, 4]
    _p_hat[4, 4] = _tmp21 * dt + 1.0 * dt * p[6, 4] + 1.0 * p[4, 4] + 1
    _p_hat[5, 4] = _tmp22 * dt + 1.0 * dt * p[7, 4] + 1.0 * p[5, 4]
    _p_hat[6, 4] = _tmp23 * dt + 1.0 * p[6, 4]
    _p_hat[7, 4] = _tmp24 * dt + 1.0 * p[7, 4]
    _p_hat[0, 5] = _tmp25 * dt + 1.0 * dt * p[2, 5] + 1.0 * p[0, 5]
    _p_hat[1, 5] = _tmp26 * dt + 1.0 * dt * p[3, 5] + 1.0 * p[1, 5]
    _p_hat[2, 5] = _tmp27 * dt + 1.0 * p[2, 5]
    _p_hat[3, 5] = _tmp28 * dt + 1.0 * p[3, 5]
    _p_hat[4, 5] = _tmp29 * dt + 1.0 * dt * p[6, 5] + 1.0 * p[4, 5]
    _p_hat[5, 5] = _tmp30 * dt + 1.0 * dt * p[7, 5] + 1.0 * p[5, 5] + 1
    _p_hat[6, 5] = _tmp31 * dt + 1.0 * p[6, 5]
    _p_hat[7, 5] = _tmp32 * dt + 1.0 * p[7, 5]
    _p_hat[0, 6] = 1.0 * _tmp17
    _p_hat[1, 6] = 1.0 * _tmp18
    _p_hat[2, 6] = _tmp19
    _p_hat[3, 6] = _tmp20
    _p_hat[4, 6] = 1.0 * _tmp21
    _p_hat[5, 6] = 1.0 * _tmp22
    _p_hat[6, 6] = _tmp23 + 1
    _p_hat[7, 6] = _tmp24
    _p_hat[0, 7] = 1.0 * _tmp25
    _p_hat[1, 7] = 1.0 * _tmp26
    _p_hat[2, 7] = _tmp27
    _p_hat[3, 7] = _tmp28
    _p_hat[4, 7] = 1.0 * _tmp29
    _p_hat[5, 7] = 1.0 * _tmp30
    _p_hat[6, 7] = _tmp31
    _p_hat[7, 7] = _tmp32 + 1
    return _x_hat, _p_hat
