# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

import math
import typing as T

import numpy
import sym


def compute_posterior(x, p, z, measurement_mask, r):
    # type: (numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray) -> T.Tuple[numpy.ndarray, numpy.ndarray]
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        x: Matrix81
        p: Matrix88
        z: Matrix21
        measurement_mask: Matrix21
        r: Matrix22

    Outputs:
        x_hat: Matrix81
        p_hat: Matrix88
    """

    # Total ops: 854

    # Input arrays
    if x.shape == (8,):
        x = x.reshape((8, 1))
    elif x.shape != (8, 1):
        raise IndexError(
            "x is expected to have shape (8, 1) or (8,); instead had shape {}".format(
                x.shape
            )
        )

    if z.shape == (2,):
        z = z.reshape((2, 1))
    elif z.shape != (2, 1):
        raise IndexError(
            "z is expected to have shape (2, 1) or (2,); instead had shape {}".format(
                z.shape
            )
        )

    if measurement_mask.shape == (2,):
        measurement_mask = measurement_mask.reshape((2, 1))
    elif measurement_mask.shape != (2, 1):
        raise IndexError(
            "measurement_mask is expected to have shape (2, 1) or (2,); instead had shape {}".format(
                measurement_mask.shape
            )
        )

    # Intermediate terms (141)
    _tmp0 = -x[1, 0] + x[5, 0]
    _tmp1 = _tmp0**2
    _tmp2 = -x[0, 0] + x[4, 0]
    _tmp3 = math.sqrt(_tmp1 + _tmp2**2)
    _tmp4 = -_tmp3 + z[0, 0]
    _tmp5 = measurement_mask[0, 0] / _tmp3
    _tmp6 = _tmp2 * _tmp5
    _tmp7 = _tmp6 * p[0, 4]
    _tmp8 = -_tmp6 * p[0, 0]
    _tmp9 = _tmp0 * _tmp5
    _tmp10 = _tmp7 + _tmp8 - _tmp9 * p[0, 1] + _tmp9 * p[0, 5]
    _tmp11 = _tmp2 + 1.0e-9 * (0.0 if _tmp2 == 0 else math.copysign(1, _tmp2)) + 5.0e-10
    _tmp12 = measurement_mask[1, 0] / (_tmp1 + _tmp11**2)
    _tmp13 = _tmp0 * _tmp12
    _tmp14 = _tmp13 * p[0, 4]
    _tmp15 = -_tmp13 * p[4, 4]
    _tmp16 = _tmp11 * _tmp12
    _tmp17 = _tmp14 + _tmp15 - _tmp16 * p[1, 4] + _tmp16 * p[5, 4]
    _tmp18 = -_tmp16 * p[1, 1]
    _tmp19 = _tmp16 * p[5, 1]
    _tmp20 = _tmp13 * p[0, 1] - _tmp13 * p[4, 1] + _tmp18 + _tmp19
    _tmp21 = _tmp16 * p[1, 5]
    _tmp22 = _tmp16 * p[5, 5]
    _tmp23 = _tmp13 * p[0, 5] - _tmp13 * p[4, 5] - _tmp21 + _tmp22
    _tmp24 = _tmp13 * p[4, 0]
    _tmp25 = _tmp13 * p[0, 0]
    _tmp26 = -_tmp16 * p[1, 0] + _tmp16 * p[5, 0] - _tmp24 + _tmp25
    _tmp27 = _tmp17 * _tmp6 - _tmp20 * _tmp9 + _tmp23 * _tmp9 - _tmp26 * _tmp6 + r[1, 0]
    _tmp28 = -_tmp9 * p[1, 1]
    _tmp29 = _tmp9 * p[5, 1]
    _tmp30 = _tmp28 + _tmp29 - _tmp6 * p[0, 1] + _tmp6 * p[4, 1]
    _tmp31 = _tmp6 * p[4, 0]
    _tmp32 = _tmp31 + _tmp8 - _tmp9 * p[1, 0] + _tmp9 * p[5, 0]
    _tmp33 = _tmp9 * p[1, 5]
    _tmp34 = _tmp9 * p[5, 5]
    _tmp35 = -_tmp33 + _tmp34 - _tmp6 * p[0, 5] + _tmp6 * p[4, 5]
    _tmp36 = _tmp6 * p[4, 4]
    _tmp37 = _tmp36 - _tmp7 - _tmp9 * p[1, 4] + _tmp9 * p[5, 4]
    _tmp38 = 1 / (
        -_tmp30 * _tmp9 - _tmp32 * _tmp6 + _tmp35 * _tmp9 + _tmp37 * _tmp6 + r[0, 0]
    )
    _tmp39 = _tmp38 * (
        _tmp13 * _tmp32 - _tmp13 * _tmp37 - _tmp16 * _tmp30 + _tmp16 * _tmp35 + r[0, 1]
    )
    _tmp40 = _tmp27 * _tmp39
    _tmp41 = 1 / (
        -_tmp13 * _tmp17
        + _tmp13 * _tmp26
        - _tmp16 * _tmp20
        + _tmp16 * _tmp23
        - _tmp40
        + r[1, 1]
    )
    _tmp42 = _tmp38 * (_tmp40 * _tmp41 + 1)
    _tmp43 = _tmp41 * (-_tmp14 - _tmp16 * p[0, 1] + _tmp16 * p[0, 5] + _tmp25)
    _tmp44 = _tmp27 * _tmp38
    _tmp45 = _tmp10 * _tmp42 - _tmp43 * _tmp44
    _tmp46 = z[1, 0] - math.atan2(_tmp0, _tmp11)
    _tmp47 = _tmp39 * _tmp41
    _tmp48 = -_tmp10 * _tmp47 + _tmp43
    _tmp49 = _tmp41 * (_tmp13 * p[1, 0] - _tmp13 * p[1, 4] + _tmp18 + _tmp21)
    _tmp50 = _tmp28 + _tmp33 - _tmp6 * p[1, 0] + _tmp6 * p[1, 4]
    _tmp51 = _tmp42 * _tmp50 - _tmp44 * _tmp49
    _tmp52 = -_tmp47 * _tmp50 + _tmp49
    _tmp53 = -_tmp6 * p[2, 0] + _tmp6 * p[2, 4] - _tmp9 * p[2, 1] + _tmp9 * p[2, 5]
    _tmp54 = _tmp41 * (
        _tmp13 * p[2, 0] - _tmp13 * p[2, 4] - _tmp16 * p[2, 1] + _tmp16 * p[2, 5]
    )
    _tmp55 = _tmp42 * _tmp53 - _tmp44 * _tmp54
    _tmp56 = -_tmp47 * _tmp53 + _tmp54
    _tmp57 = -_tmp6 * p[3, 0] + _tmp6 * p[3, 4] - _tmp9 * p[3, 1] + _tmp9 * p[3, 5]
    _tmp58 = _tmp41 * (
        _tmp13 * p[3, 0] - _tmp13 * p[3, 4] - _tmp16 * p[3, 1] + _tmp16 * p[3, 5]
    )
    _tmp59 = _tmp42 * _tmp57 - _tmp44 * _tmp58
    _tmp60 = -_tmp47 * _tmp57 + _tmp58
    _tmp61 = _tmp41 * (_tmp15 - _tmp16 * p[4, 1] + _tmp16 * p[4, 5] + _tmp24)
    _tmp62 = -_tmp31 + _tmp36 - _tmp9 * p[4, 1] + _tmp9 * p[4, 5]
    _tmp63 = -_tmp47 * _tmp62 + _tmp61
    _tmp64 = _tmp42 * _tmp62 - _tmp44 * _tmp61
    _tmp65 = -_tmp29 + _tmp34 - _tmp6 * p[5, 0] + _tmp6 * p[5, 4]
    _tmp66 = _tmp41 * (_tmp13 * p[5, 0] - _tmp13 * p[5, 4] - _tmp19 + _tmp22)
    _tmp67 = _tmp42 * _tmp65 - _tmp44 * _tmp66
    _tmp68 = -_tmp47 * _tmp65 + _tmp66
    _tmp69 = -_tmp6 * p[6, 0] + _tmp6 * p[6, 4] - _tmp9 * p[6, 1] + _tmp9 * p[6, 5]
    _tmp70 = _tmp41 * (
        _tmp13 * p[6, 0] - _tmp13 * p[6, 4] - _tmp16 * p[6, 1] + _tmp16 * p[6, 5]
    )
    _tmp71 = _tmp42 * _tmp69 - _tmp44 * _tmp70
    _tmp72 = -_tmp47 * _tmp69 + _tmp70
    _tmp73 = _tmp41 * (
        _tmp13 * p[7, 0] - _tmp13 * p[7, 4] - _tmp16 * p[7, 1] + _tmp16 * p[7, 5]
    )
    _tmp74 = -_tmp6 * p[7, 0] + _tmp6 * p[7, 4] - _tmp9 * p[7, 1] + _tmp9 * p[7, 5]
    _tmp75 = _tmp42 * _tmp74 - _tmp44 * _tmp73
    _tmp76 = -_tmp47 * _tmp74 + _tmp73
    _tmp77 = _tmp13 * _tmp48
    _tmp78 = _tmp45 * _tmp6
    _tmp79 = -_tmp77 + _tmp78
    _tmp80 = -_tmp77 + _tmp78 + 1
    _tmp81 = _tmp16 * _tmp48
    _tmp82 = _tmp45 * _tmp9
    _tmp83 = _tmp81 + _tmp82
    _tmp84 = -_tmp81 - _tmp82
    _tmp85 = _tmp16 * _tmp52
    _tmp86 = _tmp51 * _tmp9
    _tmp87 = _tmp85 + _tmp86 + 1
    _tmp88 = _tmp85 + _tmp86
    _tmp89 = _tmp13 * _tmp52
    _tmp90 = _tmp51 * _tmp6
    _tmp91 = -_tmp89 + _tmp90
    _tmp92 = _tmp89 - _tmp90
    _tmp93 = _tmp16 * _tmp56
    _tmp94 = _tmp55 * _tmp9
    _tmp95 = _tmp93 + _tmp94
    _tmp96 = -_tmp93 - _tmp94
    _tmp97 = _tmp13 * _tmp56
    _tmp98 = _tmp55 * _tmp6
    _tmp99 = _tmp97 - _tmp98
    _tmp100 = -_tmp97 + _tmp98
    _tmp101 = _tmp59 * _tmp9
    _tmp102 = _tmp16 * _tmp60
    _tmp103 = -_tmp101 - _tmp102
    _tmp104 = _tmp101 + _tmp102
    _tmp105 = _tmp59 * _tmp6
    _tmp106 = _tmp13 * _tmp60
    _tmp107 = _tmp105 - _tmp106
    _tmp108 = -_tmp105 + _tmp106
    _tmp109 = _tmp16 * _tmp63
    _tmp110 = _tmp64 * _tmp9
    _tmp111 = -_tmp109 - _tmp110
    _tmp112 = _tmp109 + _tmp110
    _tmp113 = _tmp13 * _tmp63
    _tmp114 = _tmp6 * _tmp64
    _tmp115 = _tmp113 - _tmp114 + 1
    _tmp116 = _tmp113 - _tmp114
    _tmp117 = _tmp13 * _tmp68
    _tmp118 = _tmp6 * _tmp67
    _tmp119 = _tmp117 - _tmp118
    _tmp120 = -_tmp117 + _tmp118
    _tmp121 = _tmp67 * _tmp9
    _tmp122 = _tmp16 * _tmp68
    _tmp123 = -_tmp121 - _tmp122
    _tmp124 = -_tmp121 - _tmp122 + 1
    _tmp125 = _tmp16 * _tmp72
    _tmp126 = _tmp71 * _tmp9
    _tmp127 = -_tmp125 - _tmp126
    _tmp128 = _tmp125 + _tmp126
    _tmp129 = _tmp13 * _tmp72
    _tmp130 = _tmp6 * _tmp71
    _tmp131 = _tmp129 - _tmp130
    _tmp132 = -_tmp129 + _tmp130
    _tmp133 = _tmp75 * _tmp9
    _tmp134 = _tmp16 * _tmp76
    _tmp135 = -_tmp133 - _tmp134
    _tmp136 = _tmp133 + _tmp134
    _tmp137 = _tmp6 * _tmp75
    _tmp138 = _tmp13 * _tmp76
    _tmp139 = _tmp137 - _tmp138
    _tmp140 = -_tmp137 + _tmp138

    # Output terms
    _x_hat = numpy.zeros(8)
    _x_hat[0] = _tmp4 * _tmp45 + _tmp46 * _tmp48 + x[0, 0]
    _x_hat[1] = _tmp4 * _tmp51 + _tmp46 * _tmp52 + x[1, 0]
    _x_hat[2] = _tmp4 * _tmp55 + _tmp46 * _tmp56 + x[2, 0]
    _x_hat[3] = _tmp4 * _tmp59 + _tmp46 * _tmp60 + x[3, 0]
    _x_hat[4] = _tmp4 * _tmp64 + _tmp46 * _tmp63 + x[4, 0]
    _x_hat[5] = _tmp4 * _tmp67 + _tmp46 * _tmp68 + x[5, 0]
    _x_hat[6] = _tmp4 * _tmp71 + _tmp46 * _tmp72 + x[6, 0]
    _x_hat[7] = _tmp4 * _tmp75 + _tmp46 * _tmp76 + x[7, 0]
    _p_hat = numpy.zeros((8, 8))
    _p_hat[0, 0] = (
        -_tmp79 * p[4, 0] + _tmp80 * p[0, 0] - _tmp83 * p[5, 0] - _tmp84 * p[1, 0]
    )
    _p_hat[1, 0] = (
        _tmp87 * p[1, 0] - _tmp88 * p[5, 0] - _tmp91 * p[4, 0] - _tmp92 * p[0, 0]
    )
    _p_hat[2, 0] = (
        -_tmp100 * p[4, 0]
        - _tmp95 * p[5, 0]
        - _tmp96 * p[1, 0]
        - _tmp99 * p[0, 0]
        + p[2, 0]
    )
    _p_hat[3, 0] = (
        -_tmp103 * p[1, 0]
        - _tmp104 * p[5, 0]
        - _tmp107 * p[4, 0]
        - _tmp108 * p[0, 0]
        + p[3, 0]
    )
    _p_hat[4, 0] = (
        -_tmp111 * p[1, 0] - _tmp112 * p[5, 0] + _tmp115 * p[4, 0] - _tmp116 * p[0, 0]
    )
    _p_hat[5, 0] = (
        -_tmp119 * p[0, 0] - _tmp120 * p[4, 0] - _tmp123 * p[1, 0] + _tmp124 * p[5, 0]
    )
    _p_hat[6, 0] = (
        -_tmp127 * p[1, 0]
        - _tmp128 * p[5, 0]
        - _tmp131 * p[0, 0]
        - _tmp132 * p[4, 0]
        + p[6, 0]
    )
    _p_hat[7, 0] = (
        -_tmp135 * p[1, 0]
        - _tmp136 * p[5, 0]
        - _tmp139 * p[4, 0]
        - _tmp140 * p[0, 0]
        + p[7, 0]
    )
    _p_hat[0, 1] = (
        -_tmp79 * p[4, 1] + _tmp80 * p[0, 1] - _tmp83 * p[5, 1] - _tmp84 * p[1, 1]
    )
    _p_hat[1, 1] = (
        _tmp87 * p[1, 1] - _tmp88 * p[5, 1] - _tmp91 * p[4, 1] - _tmp92 * p[0, 1]
    )
    _p_hat[2, 1] = (
        -_tmp100 * p[4, 1]
        - _tmp95 * p[5, 1]
        - _tmp96 * p[1, 1]
        - _tmp99 * p[0, 1]
        + p[2, 1]
    )
    _p_hat[3, 1] = (
        -_tmp103 * p[1, 1]
        - _tmp104 * p[5, 1]
        - _tmp107 * p[4, 1]
        - _tmp108 * p[0, 1]
        + p[3, 1]
    )
    _p_hat[4, 1] = (
        -_tmp111 * p[1, 1] - _tmp112 * p[5, 1] + _tmp115 * p[4, 1] - _tmp116 * p[0, 1]
    )
    _p_hat[5, 1] = (
        -_tmp119 * p[0, 1] - _tmp120 * p[4, 1] - _tmp123 * p[1, 1] + _tmp124 * p[5, 1]
    )
    _p_hat[6, 1] = (
        -_tmp127 * p[1, 1]
        - _tmp128 * p[5, 1]
        - _tmp131 * p[0, 1]
        - _tmp132 * p[4, 1]
        + p[6, 1]
    )
    _p_hat[7, 1] = (
        -_tmp135 * p[1, 1]
        - _tmp136 * p[5, 1]
        - _tmp139 * p[4, 1]
        - _tmp140 * p[0, 1]
        + p[7, 1]
    )
    _p_hat[0, 2] = (
        -_tmp79 * p[4, 2] + _tmp80 * p[0, 2] - _tmp83 * p[5, 2] - _tmp84 * p[1, 2]
    )
    _p_hat[1, 2] = (
        _tmp87 * p[1, 2] - _tmp88 * p[5, 2] - _tmp91 * p[4, 2] - _tmp92 * p[0, 2]
    )
    _p_hat[2, 2] = (
        -_tmp100 * p[4, 2]
        - _tmp95 * p[5, 2]
        - _tmp96 * p[1, 2]
        - _tmp99 * p[0, 2]
        + p[2, 2]
    )
    _p_hat[3, 2] = (
        -_tmp103 * p[1, 2]
        - _tmp104 * p[5, 2]
        - _tmp107 * p[4, 2]
        - _tmp108 * p[0, 2]
        + p[3, 2]
    )
    _p_hat[4, 2] = (
        -_tmp111 * p[1, 2] - _tmp112 * p[5, 2] + _tmp115 * p[4, 2] - _tmp116 * p[0, 2]
    )
    _p_hat[5, 2] = (
        -_tmp119 * p[0, 2] - _tmp120 * p[4, 2] - _tmp123 * p[1, 2] + _tmp124 * p[5, 2]
    )
    _p_hat[6, 2] = (
        -_tmp127 * p[1, 2]
        - _tmp128 * p[5, 2]
        - _tmp131 * p[0, 2]
        - _tmp132 * p[4, 2]
        + p[6, 2]
    )
    _p_hat[7, 2] = (
        -_tmp135 * p[1, 2]
        - _tmp136 * p[5, 2]
        - _tmp139 * p[4, 2]
        - _tmp140 * p[0, 2]
        + p[7, 2]
    )
    _p_hat[0, 3] = (
        -_tmp79 * p[4, 3] + _tmp80 * p[0, 3] - _tmp83 * p[5, 3] - _tmp84 * p[1, 3]
    )
    _p_hat[1, 3] = (
        _tmp87 * p[1, 3] - _tmp88 * p[5, 3] - _tmp91 * p[4, 3] - _tmp92 * p[0, 3]
    )
    _p_hat[2, 3] = (
        -_tmp100 * p[4, 3]
        - _tmp95 * p[5, 3]
        - _tmp96 * p[1, 3]
        - _tmp99 * p[0, 3]
        + p[2, 3]
    )
    _p_hat[3, 3] = (
        -_tmp103 * p[1, 3]
        - _tmp104 * p[5, 3]
        - _tmp107 * p[4, 3]
        - _tmp108 * p[0, 3]
        + p[3, 3]
    )
    _p_hat[4, 3] = (
        -_tmp111 * p[1, 3] - _tmp112 * p[5, 3] + _tmp115 * p[4, 3] - _tmp116 * p[0, 3]
    )
    _p_hat[5, 3] = (
        -_tmp119 * p[0, 3] - _tmp120 * p[4, 3] - _tmp123 * p[1, 3] + _tmp124 * p[5, 3]
    )
    _p_hat[6, 3] = (
        -_tmp127 * p[1, 3]
        - _tmp128 * p[5, 3]
        - _tmp131 * p[0, 3]
        - _tmp132 * p[4, 3]
        + p[6, 3]
    )
    _p_hat[7, 3] = (
        -_tmp135 * p[1, 3]
        - _tmp136 * p[5, 3]
        - _tmp139 * p[4, 3]
        - _tmp140 * p[0, 3]
        + p[7, 3]
    )
    _p_hat[0, 4] = (
        -_tmp79 * p[4, 4] + _tmp80 * p[0, 4] - _tmp83 * p[5, 4] - _tmp84 * p[1, 4]
    )
    _p_hat[1, 4] = (
        _tmp87 * p[1, 4] - _tmp88 * p[5, 4] - _tmp91 * p[4, 4] - _tmp92 * p[0, 4]
    )
    _p_hat[2, 4] = (
        -_tmp100 * p[4, 4]
        - _tmp95 * p[5, 4]
        - _tmp96 * p[1, 4]
        - _tmp99 * p[0, 4]
        + p[2, 4]
    )
    _p_hat[3, 4] = (
        -_tmp103 * p[1, 4]
        - _tmp104 * p[5, 4]
        - _tmp107 * p[4, 4]
        - _tmp108 * p[0, 4]
        + p[3, 4]
    )
    _p_hat[4, 4] = (
        -_tmp111 * p[1, 4] - _tmp112 * p[5, 4] + _tmp115 * p[4, 4] - _tmp116 * p[0, 4]
    )
    _p_hat[5, 4] = (
        -_tmp119 * p[0, 4] - _tmp120 * p[4, 4] - _tmp123 * p[1, 4] + _tmp124 * p[5, 4]
    )
    _p_hat[6, 4] = (
        -_tmp127 * p[1, 4]
        - _tmp128 * p[5, 4]
        - _tmp131 * p[0, 4]
        - _tmp132 * p[4, 4]
        + p[6, 4]
    )
    _p_hat[7, 4] = (
        -_tmp135 * p[1, 4]
        - _tmp136 * p[5, 4]
        - _tmp139 * p[4, 4]
        - _tmp140 * p[0, 4]
        + p[7, 4]
    )
    _p_hat[0, 5] = (
        -_tmp79 * p[4, 5] + _tmp80 * p[0, 5] - _tmp83 * p[5, 5] - _tmp84 * p[1, 5]
    )
    _p_hat[1, 5] = (
        _tmp87 * p[1, 5] - _tmp88 * p[5, 5] - _tmp91 * p[4, 5] - _tmp92 * p[0, 5]
    )
    _p_hat[2, 5] = (
        -_tmp100 * p[4, 5]
        - _tmp95 * p[5, 5]
        - _tmp96 * p[1, 5]
        - _tmp99 * p[0, 5]
        + p[2, 5]
    )
    _p_hat[3, 5] = (
        -_tmp103 * p[1, 5]
        - _tmp104 * p[5, 5]
        - _tmp107 * p[4, 5]
        - _tmp108 * p[0, 5]
        + p[3, 5]
    )
    _p_hat[4, 5] = (
        -_tmp111 * p[1, 5] - _tmp112 * p[5, 5] + _tmp115 * p[4, 5] - _tmp116 * p[0, 5]
    )
    _p_hat[5, 5] = (
        -_tmp119 * p[0, 5] - _tmp120 * p[4, 5] - _tmp123 * p[1, 5] + _tmp124 * p[5, 5]
    )
    _p_hat[6, 5] = (
        -_tmp127 * p[1, 5]
        - _tmp128 * p[5, 5]
        - _tmp131 * p[0, 5]
        - _tmp132 * p[4, 5]
        + p[6, 5]
    )
    _p_hat[7, 5] = (
        -_tmp135 * p[1, 5]
        - _tmp136 * p[5, 5]
        - _tmp139 * p[4, 5]
        - _tmp140 * p[0, 5]
        + p[7, 5]
    )
    _p_hat[0, 6] = (
        -_tmp79 * p[4, 6] + _tmp80 * p[0, 6] - _tmp83 * p[5, 6] - _tmp84 * p[1, 6]
    )
    _p_hat[1, 6] = (
        _tmp87 * p[1, 6] - _tmp88 * p[5, 6] - _tmp91 * p[4, 6] - _tmp92 * p[0, 6]
    )
    _p_hat[2, 6] = (
        -_tmp100 * p[4, 6]
        - _tmp95 * p[5, 6]
        - _tmp96 * p[1, 6]
        - _tmp99 * p[0, 6]
        + p[2, 6]
    )
    _p_hat[3, 6] = (
        -_tmp103 * p[1, 6]
        - _tmp104 * p[5, 6]
        - _tmp107 * p[4, 6]
        - _tmp108 * p[0, 6]
        + p[3, 6]
    )
    _p_hat[4, 6] = (
        -_tmp111 * p[1, 6] - _tmp112 * p[5, 6] + _tmp115 * p[4, 6] - _tmp116 * p[0, 6]
    )
    _p_hat[5, 6] = (
        -_tmp119 * p[0, 6] - _tmp120 * p[4, 6] - _tmp123 * p[1, 6] + _tmp124 * p[5, 6]
    )
    _p_hat[6, 6] = (
        -_tmp127 * p[1, 6]
        - _tmp128 * p[5, 6]
        - _tmp131 * p[0, 6]
        - _tmp132 * p[4, 6]
        + p[6, 6]
    )
    _p_hat[7, 6] = (
        -_tmp135 * p[1, 6]
        - _tmp136 * p[5, 6]
        - _tmp139 * p[4, 6]
        - _tmp140 * p[0, 6]
        + p[7, 6]
    )
    _p_hat[0, 7] = (
        -_tmp79 * p[4, 7] + _tmp80 * p[0, 7] - _tmp83 * p[5, 7] - _tmp84 * p[1, 7]
    )
    _p_hat[1, 7] = (
        _tmp87 * p[1, 7] - _tmp88 * p[5, 7] - _tmp91 * p[4, 7] - _tmp92 * p[0, 7]
    )
    _p_hat[2, 7] = (
        -_tmp100 * p[4, 7]
        - _tmp95 * p[5, 7]
        - _tmp96 * p[1, 7]
        - _tmp99 * p[0, 7]
        + p[2, 7]
    )
    _p_hat[3, 7] = (
        -_tmp103 * p[1, 7]
        - _tmp104 * p[5, 7]
        - _tmp107 * p[4, 7]
        - _tmp108 * p[0, 7]
        + p[3, 7]
    )
    _p_hat[4, 7] = (
        -_tmp111 * p[1, 7] - _tmp112 * p[5, 7] + _tmp115 * p[4, 7] - _tmp116 * p[0, 7]
    )
    _p_hat[5, 7] = (
        -_tmp119 * p[0, 7] - _tmp120 * p[4, 7] - _tmp123 * p[1, 7] + _tmp124 * p[5, 7]
    )
    _p_hat[6, 7] = (
        -_tmp127 * p[1, 7]
        - _tmp128 * p[5, 7]
        - _tmp131 * p[0, 7]
        - _tmp132 * p[4, 7]
        + p[6, 7]
    )
    _p_hat[7, 7] = (
        -_tmp135 * p[1, 7]
        - _tmp136 * p[5, 7]
        - _tmp139 * p[4, 7]
        - _tmp140 * p[0, 7]
        + p[7, 7]
    )
    return _x_hat, _p_hat
