# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

import math
import typing as T

import numpy
import sym


def compute_posterior(x, p, z, measurement_mask, r, params):
    # type: (numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, T.Any) -> T.Tuple[numpy.ndarray, numpy.ndarray]
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        x: Matrix41
        p: Matrix44
        z: Matrix51
        measurement_mask: Matrix51
        r: Matrix55
        params: Values

    Outputs:
        x_hat: Matrix41
        p_hat: Matrix44
    """

    # Total ops: 696

    # Input arrays
    if x.shape == (4,):
        x = x.reshape((4, 1))
    elif x.shape != (4, 1):
        raise IndexError(
            "x is expected to have shape (4, 1) or (4,); instead had shape {}".format(
                x.shape
            )
        )

    if z.shape == (5,):
        z = z.reshape((5, 1))
    elif z.shape != (5, 1):
        raise IndexError(
            "z is expected to have shape (5, 1) or (5,); instead had shape {}".format(
                z.shape
            )
        )

    if measurement_mask.shape == (5,):
        measurement_mask = measurement_mask.reshape((5, 1))
    elif measurement_mask.shape != (5, 1):
        raise IndexError(
            "measurement_mask is expected to have shape (5, 1) or (5,); instead had shape {}".format(
                measurement_mask.shape
            )
        )

    # Intermediate terms (147)
    _tmp0 = measurement_mask[1, 0] * measurement_mask[2, 0]
    _tmp1 = measurement_mask[0, 0] * measurement_mask[2, 0]
    _tmp2 = _tmp1 * p[0, 2] + r[0, 2]
    _tmp3 = 1 / (measurement_mask[0, 0] ** 2 * p[0, 0] + r[0, 0])
    _tmp4 = measurement_mask[0, 0] * measurement_mask[1, 0]
    _tmp5 = _tmp3 * (_tmp4 * p[1, 0] + r[1, 0])
    _tmp6 = _tmp0 * p[1, 2] - _tmp2 * _tmp5 + r[1, 2]
    _tmp7 = _tmp4 * p[0, 1] + r[0, 1]
    _tmp8 = _tmp3 * (_tmp1 * p[2, 0] + r[2, 0])
    _tmp9 = 1 / (-_tmp5 * _tmp7 + measurement_mask[1, 0] ** 2 * p[1, 1] + r[1, 1])
    _tmp10 = _tmp9 * (_tmp0 * p[2, 1] - _tmp7 * _tmp8 + r[2, 1])
    _tmp11 = 1 / (
        -_tmp10 * _tmp6
        - _tmp2 * _tmp8
        + measurement_mask[2, 0] ** 2 * p[2, 2]
        + r[2, 2]
    )
    _tmp12 = math.sqrt(x[2, 0] ** 2 + x[3, 0] ** 2)
    _tmp13 = measurement_mask[4, 0] / _tmp12
    _tmp14 = _tmp13 * x[3, 0]
    _tmp15 = _tmp13 * x[2, 0]
    _tmp16 = _tmp3 * (
        measurement_mask[0, 0] * (_tmp14 * p[3, 0] + _tmp15 * p[2, 0]) + r[4, 0]
    )
    _tmp17 = _tmp9 * (
        -_tmp16 * _tmp7
        + measurement_mask[1, 0] * (_tmp14 * p[3, 1] + _tmp15 * p[2, 1])
        + r[4, 1]
    )
    _tmp18 = _tmp15 * p[2, 2]
    _tmp19 = _tmp14 * p[3, 2] + _tmp18
    _tmp20 = _tmp11 * (
        -_tmp16 * _tmp2 - _tmp17 * _tmp6 + _tmp19 * measurement_mask[2, 0] + r[4, 2]
    )
    _tmp21 = measurement_mask[1, 0] * measurement_mask[3, 0]
    _tmp22 = measurement_mask[0, 0] * measurement_mask[3, 0]
    _tmp23 = _tmp3 * (_tmp22 * p[3, 0] + r[3, 0])
    _tmp24 = _tmp9 * (_tmp21 * p[3, 1] - _tmp23 * _tmp7 + r[3, 1])
    _tmp25 = measurement_mask[2, 0] * measurement_mask[3, 0]
    _tmp26 = _tmp11 * (-_tmp2 * _tmp23 - _tmp24 * _tmp6 + _tmp25 * p[3, 2] + r[3, 2])
    _tmp27 = _tmp22 * p[0, 3] + r[0, 3]
    _tmp28 = _tmp21 * p[1, 3] - _tmp27 * _tmp5 + r[1, 3]
    _tmp29 = -_tmp10 * _tmp28 + _tmp25 * p[2, 3] - _tmp27 * _tmp8 + r[2, 3]
    _tmp30 = 1 / (
        -_tmp23 * _tmp27
        - _tmp24 * _tmp28
        - _tmp26 * _tmp29
        + measurement_mask[3, 0] ** 2 * p[3, 3]
        + r[3, 3]
    )
    _tmp31 = _tmp14 * p[3, 3]
    _tmp32 = _tmp15 * p[2, 3] + _tmp31
    _tmp33 = _tmp30 * (
        -_tmp16 * _tmp27
        - _tmp17 * _tmp28
        - _tmp20 * _tmp29
        + _tmp32 * measurement_mask[3, 0]
        + r[4, 3]
    )
    _tmp34 = -_tmp20 + _tmp26 * _tmp33
    _tmp35 = _tmp14 * p[0, 3]
    _tmp36 = _tmp15 * p[0, 2]
    _tmp37 = _tmp35 * measurement_mask[0, 0] + _tmp36 * measurement_mask[0, 0] + r[0, 4]
    _tmp38 = _tmp14 * p[1, 3]
    _tmp39 = _tmp15 * p[1, 2]
    _tmp40 = (
        -_tmp37 * _tmp5
        + _tmp38 * measurement_mask[1, 0]
        + _tmp39 * measurement_mask[1, 0]
        + r[1, 4]
    )
    _tmp41 = _tmp14 * p[2, 3]
    _tmp42 = (
        -_tmp10 * _tmp40
        + _tmp18 * measurement_mask[2, 0]
        - _tmp37 * _tmp8
        + _tmp41 * measurement_mask[2, 0]
        + r[2, 4]
    )
    _tmp43 = _tmp15 * p[3, 2]
    _tmp44 = (
        -_tmp23 * _tmp37
        - _tmp24 * _tmp40
        - _tmp26 * _tmp42
        + _tmp31 * measurement_mask[3, 0]
        + _tmp43 * measurement_mask[3, 0]
        + r[3, 4]
    )
    _tmp45 = 1 / (
        _tmp14 * _tmp32
        + _tmp15 * _tmp19
        - _tmp16 * _tmp37
        - _tmp17 * _tmp40
        - _tmp20 * _tmp42
        - _tmp33 * _tmp44
        + r[4, 4]
    )
    _tmp46 = _tmp45 * (_tmp35 + _tmp36)
    _tmp47 = _tmp42 * _tmp45
    _tmp48 = _tmp44 * _tmp45
    _tmp49 = -_tmp26 - _tmp34 * _tmp48
    _tmp50 = _tmp29 * _tmp30
    _tmp51 = -_tmp34 * _tmp47 - _tmp49 * _tmp50 + 1
    _tmp52 = _tmp11 * _tmp2
    _tmp53 = _tmp27 * _tmp30
    _tmp54 = _tmp28 * _tmp30
    _tmp55 = _tmp11 * _tmp6
    _tmp56 = _tmp40 * _tmp45
    _tmp57 = -_tmp34 * _tmp56 - _tmp49 * _tmp54 - _tmp51 * _tmp55
    _tmp58 = _tmp7 * _tmp9
    _tmp59 = _tmp37 * _tmp45
    _tmp60 = _tmp3 * measurement_mask[0, 0]
    _tmp61 = _tmp60 * (
        -_tmp34 * _tmp59 - _tmp49 * _tmp53 - _tmp51 * _tmp52 - _tmp57 * _tmp58
    )
    _tmp62 = _tmp11 * measurement_mask[2, 0]
    _tmp63 = _tmp51 * _tmp62
    _tmp64 = _tmp30 * measurement_mask[3, 0]
    _tmp65 = _tmp64 * p[0, 3]
    _tmp66 = _tmp9 * measurement_mask[1, 0]
    _tmp67 = _tmp57 * _tmp66
    _tmp68 = (
        _tmp34 * _tmp46
        + _tmp49 * _tmp65
        + _tmp61 * p[0, 0]
        + _tmp63 * p[0, 2]
        + _tmp67 * p[0, 1]
    )
    _tmp69 = -x[2, 0] + z[2, 0]
    _tmp70 = _tmp33 * _tmp48 + 1
    _tmp71 = _tmp33 * _tmp47 - _tmp50 * _tmp70
    _tmp72 = _tmp62 * _tmp71
    _tmp73 = _tmp33 * _tmp56 - _tmp54 * _tmp70 - _tmp55 * _tmp71
    _tmp74 = _tmp60 * (
        _tmp33 * _tmp59 - _tmp52 * _tmp71 - _tmp53 * _tmp70 - _tmp58 * _tmp73
    )
    _tmp75 = _tmp66 * _tmp73
    _tmp76 = _tmp64 * _tmp70
    _tmp77 = (
        -_tmp33 * _tmp46
        + _tmp72 * p[0, 2]
        + _tmp74 * p[0, 0]
        + _tmp75 * p[0, 1]
        + _tmp76 * p[0, 3]
    )
    _tmp78 = -x[3, 0] + z[3, 0]
    _tmp79 = -_tmp12 + z[4, 0]
    _tmp80 = -_tmp47 + _tmp48 * _tmp50
    _tmp81 = _tmp48 * _tmp54 - _tmp55 * _tmp80 - _tmp56
    _tmp82 = _tmp66 * _tmp81
    _tmp83 = _tmp62 * _tmp80
    _tmp84 = _tmp60 * (_tmp48 * _tmp53 - _tmp52 * _tmp80 - _tmp58 * _tmp81 - _tmp59)
    _tmp85 = (
        _tmp46
        - _tmp48 * _tmp65
        + _tmp82 * p[0, 1]
        + _tmp83 * p[0, 2]
        + _tmp84 * p[0, 0]
    )
    _tmp86 = -x[1, 0] + z[1, 0]
    _tmp87 = _tmp10 * _tmp26 - _tmp24
    _tmp88 = _tmp10 * _tmp20 - _tmp17 - _tmp33 * _tmp87
    _tmp89 = -_tmp48 * _tmp88 + _tmp87
    _tmp90 = _tmp64 * _tmp89
    _tmp91 = -_tmp10 - _tmp47 * _tmp88 - _tmp50 * _tmp89
    _tmp92 = -_tmp54 * _tmp89 - _tmp55 * _tmp91 - _tmp56 * _tmp88 + 1
    _tmp93 = _tmp60 * (
        -_tmp52 * _tmp91 - _tmp53 * _tmp89 - _tmp58 * _tmp92 - _tmp59 * _tmp88
    )
    _tmp94 = _tmp62 * _tmp91
    _tmp95 = _tmp66 * _tmp92
    _tmp96 = (
        _tmp46 * _tmp88
        + _tmp90 * p[0, 3]
        + _tmp93 * p[0, 0]
        + _tmp94 * p[0, 2]
        + _tmp95 * p[0, 1]
    )
    _tmp97 = -x[0, 0] + z[0, 0]
    _tmp98 = _tmp10 * _tmp5 - _tmp8
    _tmp99 = -_tmp23 + _tmp24 * _tmp5 - _tmp26 * _tmp98
    _tmp100 = -_tmp16 + _tmp17 * _tmp5 - _tmp20 * _tmp98 - _tmp33 * _tmp99
    _tmp101 = -_tmp100 * _tmp48 + _tmp99
    _tmp102 = -_tmp100 * _tmp47 - _tmp101 * _tmp50 + _tmp98
    _tmp103 = -_tmp100 * _tmp56 - _tmp101 * _tmp54 - _tmp102 * _tmp55 - _tmp5
    _tmp104 = _tmp60 * (
        -_tmp100 * _tmp59 - _tmp101 * _tmp53 - _tmp102 * _tmp52 - _tmp103 * _tmp58 + 1
    )
    _tmp105 = _tmp102 * _tmp62
    _tmp106 = _tmp103 * _tmp66
    _tmp107 = (
        _tmp100 * _tmp46
        + _tmp101 * _tmp65
        + _tmp104 * p[0, 0]
        + _tmp105 * p[0, 2]
        + _tmp106 * p[0, 1]
    )
    _tmp108 = _tmp45 * (_tmp38 + _tmp39)
    _tmp109 = (
        _tmp108 * _tmp88
        + _tmp90 * p[1, 3]
        + _tmp93 * p[1, 0]
        + _tmp94 * p[1, 2]
        + _tmp95 * p[1, 1]
    )
    _tmp110 = _tmp64 * p[1, 3]
    _tmp111 = (
        _tmp108 * _tmp34
        + _tmp110 * _tmp49
        + _tmp61 * p[1, 0]
        + _tmp63 * p[1, 2]
        + _tmp67 * p[1, 1]
    )
    _tmp112 = (
        _tmp108
        - _tmp110 * _tmp48
        + _tmp82 * p[1, 1]
        + _tmp83 * p[1, 2]
        + _tmp84 * p[1, 0]
    )
    _tmp113 = (
        -_tmp108 * _tmp33
        + _tmp72 * p[1, 2]
        + _tmp74 * p[1, 0]
        + _tmp75 * p[1, 1]
        + _tmp76 * p[1, 3]
    )
    _tmp114 = (
        _tmp100 * _tmp108
        + _tmp101 * _tmp110
        + _tmp104 * p[1, 0]
        + _tmp105 * p[1, 2]
        + _tmp106 * p[1, 1]
    )
    _tmp115 = _tmp45 * (_tmp18 + _tmp41)
    _tmp116 = _tmp64 * p[2, 3]
    _tmp117 = (
        -_tmp115 * _tmp33
        + _tmp116 * _tmp70
        + _tmp72 * p[2, 2]
        + _tmp74 * p[2, 0]
        + _tmp75 * p[2, 1]
    )
    _tmp118 = (
        _tmp115 * _tmp34
        + _tmp116 * _tmp49
        + _tmp61 * p[2, 0]
        + _tmp63 * p[2, 2]
        + _tmp67 * p[2, 1]
    )
    _tmp119 = (
        _tmp115 * _tmp88
        + _tmp116 * _tmp89
        + _tmp93 * p[2, 0]
        + _tmp94 * p[2, 2]
        + _tmp95 * p[2, 1]
    )
    _tmp120 = (
        _tmp100 * _tmp115
        + _tmp101 * _tmp116
        + _tmp104 * p[2, 0]
        + _tmp105 * p[2, 2]
        + _tmp106 * p[2, 1]
    )
    _tmp121 = (
        _tmp115
        - _tmp116 * _tmp48
        + _tmp82 * p[2, 1]
        + _tmp83 * p[2, 2]
        + _tmp84 * p[2, 0]
    )
    _tmp122 = _tmp45 * (_tmp31 + _tmp43)
    _tmp123 = _tmp64 * p[3, 3]
    _tmp124 = (
        _tmp122 * _tmp34
        + _tmp123 * _tmp49
        + _tmp61 * p[3, 0]
        + _tmp63 * p[3, 2]
        + _tmp67 * p[3, 1]
    )
    _tmp125 = (
        _tmp122
        - _tmp123 * _tmp48
        + _tmp82 * p[3, 1]
        + _tmp83 * p[3, 2]
        + _tmp84 * p[3, 0]
    )
    _tmp126 = (
        _tmp100 * _tmp122
        + _tmp101 * _tmp123
        + _tmp104 * p[3, 0]
        + _tmp105 * p[3, 2]
        + _tmp106 * p[3, 1]
    )
    _tmp127 = (
        -_tmp122 * _tmp33
        + _tmp72 * p[3, 2]
        + _tmp74 * p[3, 0]
        + _tmp75 * p[3, 1]
        + _tmp76 * p[3, 3]
    )
    _tmp128 = (
        _tmp122 * _tmp88
        + _tmp90 * p[3, 3]
        + _tmp93 * p[3, 0]
        + _tmp94 * p[3, 2]
        + _tmp95 * p[3, 1]
    )
    _tmp129 = _tmp15 * _tmp85 + _tmp68 * measurement_mask[2, 0]
    _tmp130 = -_tmp107 * measurement_mask[0, 0] + 1
    _tmp131 = measurement_mask[1, 0] * p[1, 0]
    _tmp132 = _tmp14 * _tmp85 + _tmp77 * measurement_mask[3, 0]
    _tmp133 = -_tmp109 * measurement_mask[1, 0] + 1
    _tmp134 = _tmp111 * measurement_mask[2, 0] + _tmp112 * _tmp15
    _tmp135 = _tmp114 * measurement_mask[0, 0]
    _tmp136 = _tmp112 * _tmp14 + _tmp113 * measurement_mask[3, 0]
    _tmp137 = _tmp120 * measurement_mask[0, 0]
    _tmp138 = _tmp117 * measurement_mask[3, 0] + _tmp121 * _tmp14
    _tmp139 = -_tmp118 * measurement_mask[2, 0] - _tmp121 * _tmp15 + 1
    _tmp140 = _tmp124 * measurement_mask[2, 0] + _tmp125 * _tmp15
    _tmp141 = _tmp126 * measurement_mask[0, 0]
    _tmp142 = -_tmp125 * _tmp14 - _tmp127 * measurement_mask[3, 0] + 1
    _tmp143 = _tmp96 * measurement_mask[1, 0]
    _tmp144 = measurement_mask[0, 0] * p[0, 1]
    _tmp145 = _tmp119 * measurement_mask[1, 0]
    _tmp146 = _tmp128 * measurement_mask[1, 0]

    # Output terms
    _x_hat = numpy.zeros(4)
    _x_hat[0] = (
        _tmp107 * _tmp97
        + _tmp68 * _tmp69
        + _tmp77 * _tmp78
        + _tmp79 * _tmp85
        + _tmp86 * _tmp96
        + x[0, 0]
    )
    _x_hat[1] = (
        _tmp109 * _tmp86
        + _tmp111 * _tmp69
        + _tmp112 * _tmp79
        + _tmp113 * _tmp78
        + _tmp114 * _tmp97
        + x[1, 0]
    )
    _x_hat[2] = (
        _tmp117 * _tmp78
        + _tmp118 * _tmp69
        + _tmp119 * _tmp86
        + _tmp120 * _tmp97
        + _tmp121 * _tmp79
        + x[2, 0]
    )
    _x_hat[3] = (
        _tmp124 * _tmp69
        + _tmp125 * _tmp79
        + _tmp126 * _tmp97
        + _tmp127 * _tmp78
        + _tmp128 * _tmp86
        + x[3, 0]
    )
    _p_hat = numpy.zeros((4, 4))
    _p_hat[0, 0] = (
        -_tmp129 * p[2, 0] + _tmp130 * p[0, 0] - _tmp131 * _tmp96 - _tmp132 * p[3, 0]
    )
    _p_hat[1, 0] = (
        _tmp133 * p[1, 0] - _tmp134 * p[2, 0] - _tmp135 * p[0, 0] - _tmp136 * p[3, 0]
    )
    _p_hat[2, 0] = (
        -_tmp119 * _tmp131 - _tmp137 * p[0, 0] - _tmp138 * p[3, 0] + _tmp139 * p[2, 0]
    )
    _p_hat[3, 0] = (
        -_tmp128 * _tmp131 - _tmp140 * p[2, 0] - _tmp141 * p[0, 0] + _tmp142 * p[3, 0]
    )
    _p_hat[0, 1] = (
        -_tmp129 * p[2, 1] + _tmp130 * p[0, 1] - _tmp132 * p[3, 1] - _tmp143 * p[1, 1]
    )
    _p_hat[1, 1] = (
        -_tmp114 * _tmp144 + _tmp133 * p[1, 1] - _tmp134 * p[2, 1] - _tmp136 * p[3, 1]
    )
    _p_hat[2, 1] = (
        -_tmp120 * _tmp144 - _tmp138 * p[3, 1] + _tmp139 * p[2, 1] - _tmp145 * p[1, 1]
    )
    _p_hat[3, 1] = (
        -_tmp140 * p[2, 1] - _tmp141 * p[0, 1] + _tmp142 * p[3, 1] - _tmp146 * p[1, 1]
    )
    _p_hat[0, 2] = (
        -_tmp129 * p[2, 2] + _tmp130 * p[0, 2] - _tmp132 * p[3, 2] - _tmp143 * p[1, 2]
    )
    _p_hat[1, 2] = (
        _tmp133 * p[1, 2] - _tmp134 * p[2, 2] - _tmp135 * p[0, 2] - _tmp136 * p[3, 2]
    )
    _p_hat[2, 2] = (
        -_tmp137 * p[0, 2] - _tmp138 * p[3, 2] + _tmp139 * p[2, 2] - _tmp145 * p[1, 2]
    )
    _p_hat[3, 2] = (
        -_tmp140 * p[2, 2] - _tmp141 * p[0, 2] + _tmp142 * p[3, 2] - _tmp146 * p[1, 2]
    )
    _p_hat[0, 3] = (
        -_tmp129 * p[2, 3] + _tmp130 * p[0, 3] - _tmp132 * p[3, 3] - _tmp143 * p[1, 3]
    )
    _p_hat[1, 3] = (
        _tmp133 * p[1, 3] - _tmp134 * p[2, 3] - _tmp135 * p[0, 3] - _tmp136 * p[3, 3]
    )
    _p_hat[2, 3] = (
        -_tmp137 * p[0, 3] - _tmp138 * p[3, 3] + _tmp139 * p[2, 3] - _tmp145 * p[1, 3]
    )
    _p_hat[3, 3] = (
        -_tmp140 * p[2, 3] - _tmp141 * p[0, 3] + _tmp142 * p[3, 3] - _tmp146 * p[1, 3]
    )
    return _x_hat, _p_hat
