# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

import math
import typing as T

import numpy
import sym


def compute_prior(dt, x, p, u, params):
    # type: (float, numpy.ndarray, numpy.ndarray, numpy.ndarray, T.Any) -> T.Tuple[numpy.ndarray, numpy.ndarray]
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        dt: Scalar
        x: Matrix41
        p: Matrix44
        u: Matrix21
        params: Values

    Outputs:
        x_hat: Matrix41
        p_hat: Matrix44
    """

    # Total ops: 92

    # Input arrays
    if x.shape == (4,):
        x = x.reshape((4, 1))
    elif x.shape != (4, 1):
        raise IndexError(
            "x is expected to have shape (4, 1) or (4,); instead had shape {}".format(
                x.shape
            )
        )

    if u.shape == (2,):
        u = u.reshape((2, 1))
    elif u.shape != (2, 1):
        raise IndexError(
            "u is expected to have shape (2, 1) or (2,); instead had shape {}".format(
                u.shape
            )
        )

    # Intermediate terms (12)
    _tmp0 = dt / params.m
    _tmp1 = _tmp0 * u[0, 0]
    _tmp2 = 4.0 * dt
    _tmp3 = _tmp0 * u[1, 0]
    _tmp4 = dt * p[2, 2] + 1.0 * p[0, 2]
    _tmp5 = dt * p[3, 2] + 1.0 * p[1, 2]
    _tmp6 = 1.0 * p[2, 2]
    _tmp7 = 1.0 * p[3, 2]
    _tmp8 = dt * p[2, 3] + 1.0 * p[0, 3]
    _tmp9 = dt * p[3, 3] + 1.0 * p[1, 3]
    _tmp10 = 1.0 * p[2, 3]
    _tmp11 = 1.0 * p[3, 3]

    # Output terms
    _x_hat = numpy.zeros(4)
    _x_hat[0] = (
        0.166666666666667 * _tmp2 * (0.5 * _tmp1 + x[2, 0])
        + 0.166666666666667 * dt * x[2, 0]
        + 0.166666666666667 * dt * (_tmp1 + x[2, 0])
        + x[0, 0]
    )
    _x_hat[1] = (
        0.166666666666667 * _tmp2 * (0.5 * _tmp3 + x[3, 0])
        + 0.166666666666667 * dt * x[3, 0]
        + 0.166666666666667 * dt * (_tmp3 + x[3, 0])
        + x[1, 0]
    )
    _x_hat[2] = 1.0 * _tmp1 + x[2, 0]
    _x_hat[3] = 1.0 * _tmp3 + x[3, 0]
    _p_hat = numpy.zeros((4, 4))
    _p_hat[0, 0] = _tmp4 * dt + 1.0 * dt * p[2, 0] + 1.0 * p[0, 0] + 1
    _p_hat[1, 0] = _tmp5 * dt + 1.0 * dt * p[3, 0] + 1.0 * p[1, 0]
    _p_hat[2, 0] = _tmp6 * dt + 1.0 * p[2, 0]
    _p_hat[3, 0] = _tmp7 * dt + 1.0 * p[3, 0]
    _p_hat[0, 1] = _tmp8 * dt + 1.0 * dt * p[2, 1] + 1.0 * p[0, 1]
    _p_hat[1, 1] = _tmp9 * dt + 1.0 * dt * p[3, 1] + 1.0 * p[1, 1] + 1
    _p_hat[2, 1] = _tmp10 * dt + 1.0 * p[2, 1]
    _p_hat[3, 1] = _tmp11 * dt + 1.0 * p[3, 1]
    _p_hat[0, 2] = 1.0 * _tmp4
    _p_hat[1, 2] = 1.0 * _tmp5
    _p_hat[2, 2] = _tmp6 + 1
    _p_hat[3, 2] = _tmp7
    _p_hat[0, 3] = 1.0 * _tmp8
    _p_hat[1, 3] = 1.0 * _tmp9
    _p_hat[2, 3] = _tmp10
    _p_hat[3, 3] = _tmp11 + 1
    return _x_hat, _p_hat
