# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

import math
import typing as T

import numpy
import sym


def compute_posterior(x, p, z, measurement_mask, r):
    # type: (numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray) -> T.Tuple[numpy.ndarray, numpy.ndarray]
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        x: Matrix41
        p: Matrix44
        z: Matrix41
        measurement_mask: Matrix41
        r: Matrix0_0

    Outputs:
        x_hat: Matrix41
        p_hat: Matrix44
    """

    # Total ops: 417

    # Input arrays
    if x.shape == (4,):
        x = x.reshape((4, 1))
    elif x.shape != (4, 1):
        raise IndexError(
            "x is expected to have shape (4, 1) or (4,); instead had shape {}".format(
                x.shape
            )
        )

    if z.shape == (4,):
        z = z.reshape((4, 1))
    elif z.shape != (4, 1):
        raise IndexError(
            "z is expected to have shape (4, 1) or (4,); instead had shape {}".format(
                z.shape
            )
        )

    if measurement_mask.shape == (4,):
        measurement_mask = measurement_mask.reshape((4, 1))
    elif measurement_mask.shape != (4, 1):
        raise IndexError(
            "measurement_mask is expected to have shape (4, 1) or (4,); instead had shape {}".format(
                measurement_mask.shape
            )
        )

    # Intermediate terms (102)
    _tmp0 = measurement_mask[1, 0] * measurement_mask[2, 0]
    _tmp1 = 1 / p[0, 0]
    _tmp2 = _tmp1 * p[2, 0]
    _tmp3 = measurement_mask[1, 0] ** 2
    _tmp4 = _tmp1 * p[1, 0]
    _tmp5 = 1 / (-_tmp3 * _tmp4 * p[0, 1] + _tmp3 * p[1, 1])
    _tmp6 = _tmp5 * (-_tmp0 * _tmp2 * p[0, 1] + _tmp0 * p[2, 1])
    _tmp7 = -_tmp0 * _tmp4 * p[0, 2] + _tmp0 * p[1, 2]
    _tmp8 = measurement_mask[1, 0] * measurement_mask[3, 0]
    _tmp9 = _tmp1 * p[3, 0]
    _tmp10 = _tmp5 * (-_tmp8 * _tmp9 * p[0, 1] + _tmp8 * p[3, 1])
    _tmp11 = measurement_mask[3, 0] * p[3, 2]
    _tmp12 = _tmp9 * measurement_mask[3, 0]
    _tmp13 = measurement_mask[2, 0] ** 2
    _tmp14 = 1 / (-_tmp13 * _tmp2 * p[0, 2] + _tmp13 * p[2, 2] - _tmp6 * _tmp7)
    _tmp15 = _tmp14 * (
        -_tmp10 * _tmp7
        + _tmp11 * measurement_mask[2, 0]
        - _tmp12 * measurement_mask[2, 0] * p[0, 2]
    )
    _tmp16 = -_tmp10 + _tmp15 * _tmp6
    _tmp17 = measurement_mask[3, 0] ** 2
    _tmp18 = _tmp2 * measurement_mask[2, 0]
    _tmp19 = -_tmp4 * _tmp8 * p[0, 3] + _tmp8 * p[1, 3]
    _tmp20 = measurement_mask[2, 0] * p[2, 3]
    _tmp21 = (
        -_tmp18 * measurement_mask[3, 0] * p[0, 3]
        - _tmp19 * _tmp6
        + _tmp20 * measurement_mask[3, 0]
    )
    _tmp22 = _tmp15 * _tmp21
    _tmp23 = 1 / (
        -_tmp10 * _tmp19 - _tmp17 * _tmp9 * p[0, 3] + _tmp17 * p[3, 3] - _tmp22
    )
    _tmp24 = _tmp21 * _tmp23
    _tmp25 = -_tmp16 * _tmp24 - _tmp6
    _tmp26 = _tmp14 * measurement_mask[2, 0]
    _tmp27 = _tmp25 * _tmp26
    _tmp28 = _tmp27 * p[0, 2]
    _tmp29 = _tmp14 * _tmp7
    _tmp30 = _tmp19 * _tmp23
    _tmp31 = _tmp5 * measurement_mask[1, 0]
    _tmp32 = _tmp31 * (-_tmp16 * _tmp30 - _tmp25 * _tmp29 + 1)
    _tmp33 = _tmp32 * p[0, 1]
    _tmp34 = _tmp23 * measurement_mask[3, 0]
    _tmp35 = _tmp34 * p[0, 3]
    _tmp36 = _tmp16 * _tmp35
    _tmp37 = 1 / measurement_mask[0, 0]
    _tmp38 = _tmp37 * (
        -_tmp28 * measurement_mask[0, 0]
        - _tmp33 * measurement_mask[0, 0]
        - _tmp36 * measurement_mask[0, 0]
    )
    _tmp39 = _tmp28 + _tmp33 + _tmp36 + _tmp38
    _tmp40 = -x[1, 0] + z[1, 0]
    _tmp41 = _tmp31 * (_tmp24 * _tmp29 - _tmp30)
    _tmp42 = _tmp41 * p[0, 1]
    _tmp43 = _tmp35 * measurement_mask[0, 0]
    _tmp44 = _tmp24 * _tmp26
    _tmp45 = _tmp44 * p[0, 2]
    _tmp46 = _tmp37 * (
        -_tmp42 * measurement_mask[0, 0] - _tmp43 + _tmp45 * measurement_mask[0, 0]
    )
    _tmp47 = _tmp35 + _tmp42 - _tmp45 + _tmp46
    _tmp48 = -x[3, 0] + z[3, 0]
    _tmp49 = -x[0, 0] + z[0, 0]
    _tmp50 = _tmp37 * _tmp4 * measurement_mask[1, 0]
    _tmp51 = -_tmp18 * _tmp37 + _tmp50 * _tmp6
    _tmp52 = _tmp10 * _tmp50 - _tmp12 * _tmp37 - _tmp15 * _tmp51
    _tmp53 = -_tmp24 * _tmp52 + _tmp51
    _tmp54 = _tmp31 * (-_tmp29 * _tmp53 - _tmp30 * _tmp52 - _tmp50)
    _tmp55 = _tmp54 * p[0, 1]
    _tmp56 = _tmp35 * _tmp52
    _tmp57 = _tmp26 * _tmp53
    _tmp58 = _tmp57 * p[0, 2]
    _tmp59 = _tmp37 * (
        -_tmp55 * measurement_mask[0, 0]
        - _tmp56 * measurement_mask[0, 0]
        - _tmp58 * measurement_mask[0, 0]
        + 1
    )
    _tmp60 = _tmp55 + _tmp56 + _tmp58 + _tmp59
    _tmp61 = _tmp22 * _tmp23 + 1
    _tmp62 = _tmp31 * (_tmp15 * _tmp30 - _tmp29 * _tmp61)
    _tmp63 = _tmp62 * p[0, 1]
    _tmp64 = _tmp26 * _tmp61
    _tmp65 = _tmp64 * p[0, 2]
    _tmp66 = _tmp37 * (
        _tmp15 * _tmp43
        - _tmp63 * measurement_mask[0, 0]
        - _tmp65 * measurement_mask[0, 0]
    )
    _tmp67 = -_tmp15 * _tmp35 + _tmp63 + _tmp65 + _tmp66
    _tmp68 = -x[2, 0] + z[2, 0]
    _tmp69 = _tmp34 * p[1, 3]
    _tmp70 = -_tmp15 * _tmp69 + _tmp4 * _tmp66 + _tmp62 * p[1, 1] + _tmp64 * p[1, 2]
    _tmp71 = _tmp1 * _tmp38
    _tmp72 = _tmp16 * _tmp69 + _tmp27 * p[1, 2] + _tmp32 * p[1, 1] + _tmp71 * p[1, 0]
    _tmp73 = _tmp4 * _tmp46 + _tmp41 * p[1, 1] - _tmp44 * p[1, 2] + _tmp69
    _tmp74 = _tmp4 * _tmp59 + _tmp52 * _tmp69 + _tmp54 * p[1, 1] + _tmp57 * p[1, 2]
    _tmp75 = _tmp34 * p[2, 3]
    _tmp76 = _tmp2 * _tmp59 + _tmp52 * _tmp75 + _tmp54 * p[2, 1] + _tmp57 * p[2, 2]
    _tmp77 = _tmp2 * _tmp46 + _tmp41 * p[2, 1] - _tmp44 * p[2, 2] + _tmp75
    _tmp78 = _tmp1 * _tmp66
    _tmp79 = -_tmp15 * _tmp75 + _tmp62 * p[2, 1] + _tmp64 * p[2, 2] + _tmp78 * p[2, 0]
    _tmp80 = _tmp16 * _tmp75 + _tmp27 * p[2, 2] + _tmp32 * p[2, 1] + _tmp71 * p[2, 0]
    _tmp81 = _tmp34 * p[3, 3]
    _tmp82 = _tmp16 * _tmp81 + _tmp27 * p[3, 2] + _tmp32 * p[3, 1] + _tmp71 * p[3, 0]
    _tmp83 = _tmp52 * _tmp81 + _tmp54 * p[3, 1] + _tmp57 * p[3, 2] + _tmp59 * _tmp9
    _tmp84 = _tmp41 * p[3, 1] - _tmp44 * p[3, 2] + _tmp46 * _tmp9 + _tmp81
    _tmp85 = -_tmp15 * _tmp81 + _tmp62 * p[3, 1] + _tmp64 * p[3, 2] + _tmp78 * p[3, 0]
    _tmp86 = _tmp67 * measurement_mask[2, 0]
    _tmp87 = -_tmp60 * measurement_mask[0, 0] + 1
    _tmp88 = _tmp39 * measurement_mask[1, 0]
    _tmp89 = _tmp47 * measurement_mask[3, 0]
    _tmp90 = _tmp74 * measurement_mask[0, 0]
    _tmp91 = _tmp73 * measurement_mask[3, 0]
    _tmp92 = _tmp70 * measurement_mask[2, 0]
    _tmp93 = -_tmp72 * measurement_mask[1, 0] + 1
    _tmp94 = _tmp76 * measurement_mask[0, 0]
    _tmp95 = -_tmp79 * measurement_mask[2, 0] + 1
    _tmp96 = _tmp77 * measurement_mask[3, 0]
    _tmp97 = _tmp80 * measurement_mask[1, 0]
    _tmp98 = _tmp83 * measurement_mask[0, 0]
    _tmp99 = _tmp82 * measurement_mask[1, 0]
    _tmp100 = -_tmp84 * measurement_mask[3, 0] + 1
    _tmp101 = _tmp85 * measurement_mask[2, 0]

    # Output terms
    _x_hat = numpy.zeros(4)
    _x_hat[0] = (
        _tmp39 * _tmp40 + _tmp47 * _tmp48 + _tmp49 * _tmp60 + _tmp67 * _tmp68 + x[0, 0]
    )
    _x_hat[1] = (
        _tmp40 * _tmp72 + _tmp48 * _tmp73 + _tmp49 * _tmp74 + _tmp68 * _tmp70 + x[1, 0]
    )
    _x_hat[2] = (
        _tmp40 * _tmp80 + _tmp48 * _tmp77 + _tmp49 * _tmp76 + _tmp68 * _tmp79 + x[2, 0]
    )
    _x_hat[3] = (
        _tmp40 * _tmp82 + _tmp48 * _tmp84 + _tmp49 * _tmp83 + _tmp68 * _tmp85 + x[3, 0]
    )
    _p_hat = numpy.zeros((4, 4))
    _p_hat[0, 0] = (
        -_tmp86 * p[2, 0] + _tmp87 * p[0, 0] - _tmp88 * p[1, 0] - _tmp89 * p[3, 0]
    )
    _p_hat[1, 0] = (
        -_tmp90 * p[0, 0] - _tmp91 * p[3, 0] - _tmp92 * p[2, 0] + _tmp93 * p[1, 0]
    )
    _p_hat[2, 0] = (
        -_tmp94 * p[0, 0] + _tmp95 * p[2, 0] - _tmp96 * p[3, 0] - _tmp97 * p[1, 0]
    )
    _p_hat[3, 0] = (
        _tmp100 * p[3, 0] - _tmp101 * p[2, 0] - _tmp98 * p[0, 0] - _tmp99 * p[1, 0]
    )
    _p_hat[0, 1] = (
        -_tmp86 * p[2, 1] + _tmp87 * p[0, 1] - _tmp88 * p[1, 1] - _tmp89 * p[3, 1]
    )
    _p_hat[1, 1] = (
        -_tmp90 * p[0, 1] - _tmp91 * p[3, 1] - _tmp92 * p[2, 1] + _tmp93 * p[1, 1]
    )
    _p_hat[2, 1] = (
        -_tmp94 * p[0, 1] + _tmp95 * p[2, 1] - _tmp96 * p[3, 1] - _tmp97 * p[1, 1]
    )
    _p_hat[3, 1] = (
        _tmp100 * p[3, 1] - _tmp101 * p[2, 1] - _tmp98 * p[0, 1] - _tmp99 * p[1, 1]
    )
    _p_hat[0, 2] = (
        -_tmp11 * _tmp47 - _tmp86 * p[2, 2] + _tmp87 * p[0, 2] - _tmp88 * p[1, 2]
    )
    _p_hat[1, 2] = (
        -_tmp11 * _tmp73 - _tmp90 * p[0, 2] - _tmp92 * p[2, 2] + _tmp93 * p[1, 2]
    )
    _p_hat[2, 2] = (
        -_tmp94 * p[0, 2] + _tmp95 * p[2, 2] - _tmp96 * p[3, 2] - _tmp97 * p[1, 2]
    )
    _p_hat[3, 2] = (
        _tmp100 * p[3, 2] - _tmp101 * p[2, 2] - _tmp98 * p[0, 2] - _tmp99 * p[1, 2]
    )
    _p_hat[0, 3] = (
        -_tmp20 * _tmp67 + _tmp87 * p[0, 3] - _tmp88 * p[1, 3] - _tmp89 * p[3, 3]
    )
    _p_hat[1, 3] = (
        -_tmp20 * _tmp70 - _tmp90 * p[0, 3] - _tmp91 * p[3, 3] + _tmp93 * p[1, 3]
    )
    _p_hat[2, 3] = (
        -_tmp94 * p[0, 3] + _tmp95 * p[2, 3] - _tmp96 * p[3, 3] - _tmp97 * p[1, 3]
    )
    _p_hat[3, 3] = (
        _tmp100 * p[3, 3] - _tmp101 * p[2, 3] - _tmp98 * p[0, 3] - _tmp99 * p[1, 3]
    )
    return _x_hat, _p_hat
